version: "3.8"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/garage

  mongo:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
